apiVersion: v1
kind: ConfigMap
metadata:
  name: uni-rag-config
  namespace: uni-rag
data:
  OLLAMA_BASE_URL: "http://host.docker.internal:11434"
  VECTOR_DB_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "university_documents"
  ALLOWED_ORIGINS: '["http://localhost:5173","http://localhost:3000"]'
