apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: uni-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.10.1
          ports:
            - containerPort: 6333
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: uni-rag
spec:
  selector:
    app: qdrant
  ports:
    - port: 6333
      targetPort: 6333
